spring:
  application:
    name: sourceReversal
 # datasource:
  #    url: jdbc:mysql://localhost:3306/excavate_database
   #   driver-class-name: com.mysql.cj.jdbc.Driver
    #  username: root
     # password: 12345
  #second-datasource:
   #   url: jdbc:mysql://localhost:3306/excavate_database
    #  driver-class-name: com.mysql.cj.jdbc.Driver
     # username: root
      #password: 12345
server:
  port: 9100
  ### mysql配置
